force-app/main/default/objects/Interview__c/Interview__c.object-meta.xml
<CustomObject>
    <label>Interview</label>
    <nameField>
        <displayFormat>INT-{0000}</displayFormat>
        <label>Interview Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Interview__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Interviews</relationshipLabel>
    <relationshipName>Contact_Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Feedback__c.field-meta.xml
<CustomField>
    <fullName>Feedback__c</fullName>
    <label>Feedback</label>
    <type>TextArea</type>
</CustomField>

force-app BACKUP_DELETE/main/default/objects/Interview__c/fields/Interview_Date__c.field-meta.xml
<CustomField>
    <fullName>Interview_Date__c</fullName>
    <label>Interview Date</label>
    <type>DateTime</type>
</CustomField>

force-app BACKUP_DELETE/main/default/objects/Interview__c/fields/Interview_Type__c.field-meta.xml
<CustomField>
    <fullName>Interview_Type__c</fullName>
    <inlineHelpText>Enter the Type of Interview</inlineHelpText>
    <label>Interview Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Recruiter Interview</fullName>
                <default>true</default>
                <label>Recruiter Interview</label>
            </value>
            <value>
                <fullName>Technical Interview</fullName>
            </value>
            <value>
                <fullName>Management Interview</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Interviews</relationshipLabel>
    <relationshipName>Position_Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app BACKUP_DELETE/main/default/objects/Interviewer__c/Interviewer__c.object-meta.xml
<CustomObject>
    <label>Interviewer</label>
    <nameField>
        <displayFormat>INTW-{0000}</displayFormat>
        <label>Interviewer Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviewers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Interviewer__c/fields/Interview__c.field-meta.xml
<CustomField>
    <fullName>Interview__c</fullName>
    <label>Interview</label>
    <referenceTo>Interview__c</referenceTo>
    <relationshipLabel>Interviewers</relationshipLabel>
    <relationshipName>Interviewers1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Interviewer__c/fields/Interview_Type__c.field-meta.xml
<CustomField>
    <fullName>Interview_Type__c</fullName>
    <formula>TEXT(Interview__r.Interview_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Interview Type</label>
    <type>Text</type>
</CustomField>

force-app BACKUP_DELETE/main/default/objects/Interviewer__c/fields/Interviewer__c.field-meta.xml
<CustomField>
    <fullName>Interviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Interviewers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interviewer__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <formula>Interview__r.Candidate__r.Position__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Position</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app BACKUP_DELETE/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Status of the Position</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed - Fulfilled</fullName>
            </value>
            <value>
                <fullName>Closed - Not Fulfilled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RecruitingData.cls
public with sharing class RecruitingData {
    public static Interview__c getInterviewDetails(String recordId){
        Interview__c interview = [select Id, Contact__c, Contact__r.Name , Position__c, Position__r.Name , Interview_Type__c, Interview_Date__c 
         from Interview__c where Id=:recordId WITH SECURITY_ENFORCED];
        return interview;
        //return [select Id, Contact__c, Contact__r.Name, Position__c, Position__r.Name, Interview_Type__c, Interview_Date__c 
           // from Interview__c where Id=:recordId WITH SECURITY_ENFORCED];
    }
    //For scenarios where we want to use wrapper so we can use this method in views
    //Views don't allow us to use lookup object fields like Contact__r.Name so we have to use a wrapper
    public static InterviewWrapper getInterviewDetails(String recordId, Boolean useWrapper){
        Interview__c interview = [select Id, Status__c, Feedback__c, Contact__c, Contact__r.Name , Interviewer__c, Position__c, Position__r.Name , Interview_Type__c,Interview_Date__c
                                    from Interview__c 
                                    where Id=:recordId WITH SECURITY_ENFORCED];

        InterviewWrapper wrapper = new InterviewWrapper();
        wrapper.contactName = interview.Contact__r.Name;
        wrapper.positionName = interview.Position__r.Name;
        wrapper.status = interview.Status__c;
        wrapper.interviewType = interview.Interview_Type__c;
        wrapper.interviewDate = interview.Interview_Date__c.format('MMM d, y');
        wrapper.id = interview.Id;
        wrapper.confirmationNeeded = (interview.Interviewer__c != null && (interview.Status__c == 'Applied' || interview.Status__c == 'Interview Scheduled'))?true:false;
        wrapper.feedbackNeeded = (interview.Interviewer__c != null && interview.Status__c == 'Interview Completed' && String.isEmpty(interview.Feedback__c))?true:false;

        System.debug(wrapper);
        return wrapper;
        //return [select Id, Contact__c, Contact__r.Name, Position__c, Position__r.Name, Interview_Type__c, Interview_Date__c 
           // from Interview__c where Id=:recordId WITH SECURITY_ENFORCED];
    }
    public static List<InterviewWrapper> getInterviews(Id interviewerId, Integer numberOfRecords, Boolean showOldInterviews){
        List<Interview__c> interviews = new List<Interview__c>();
        if(showOldInterviews){

            interviews = [select Id, Status__c, Feedback__c, Contact__c, Contact__r.Name , Interviewer__c, Position__c, Position__r.Name , Interview_Type__c,Interview_Date__c
               from Interview__c                 
               where Interviewer__c=:interviewerId and Status__c in ('rejected', 'selected')  
               WITH SECURITY_ENFORCED               
               order by CreatedDate desc                
               Limit :numberOfRecords ];
        }else{
            interviews = [select Id, Status__c, Feedback__c, Contact__c, Contact__r.Name , Interviewer__c, Position__c, Position__r.Name , Interview_Type__c,Interview_Date__c
                from Interview__c 
                where Interviewer__c=:interviewerId and Status__c not in ('rejected', 'selected')
                WITH SECURITY_ENFORCED
                order by CreatedDate desc
                Limit :numberOfRecords ];
        }
        InterviewWrapper wrapper = new InterviewWrapper(interviews);

        RecruitingUtil.debug(wrapper.getInterviews());
        return wrapper.getInterviews();
    }

    public class InterviewWrapper{
        public String contactName = '';
        public String positionName = '';
        public String interviewType = '';
        public String interviewDate = '';
        public String id = '';
        public String status = '';
        public String feedback = '';
        public Boolean confirmationNeeded = false;
        public Boolean feedbackNeeded = false;

        private List<InterviewWrapper> interviews = new List<InterviewWrapper>();


        public InterviewWrapper(){

        }
        public InterviewWrapper(List<Interview__c> interviews){
            for(Interview__c interview: interviews){
                InterviewWrapper wrapper = new InterviewWrapper();
                wrapper.contactName = interview.Contact__r.Name;
                wrapper.positionName = interview.Position__r.Name;
                wrapper.status = interview.Status__c;
                wrapper.interviewType = interview.Interview_Type__c;
                wrapper.interviewDate = interview.Interview_Date__c.format('MMM d, y');
                wrapper.id = interview.Id;
                wrapper.confirmationNeeded = (interview.Interviewer__c != null && (interview.Status__c == 'Applied' || interview.Status__c == 'Interview Scheduled'))?true:false;
                wrapper.feedbackNeeded = (interview.Interviewer__c != null && interview.Status__c == 'Interview Completed' && String.isEmpty(interview.Feedback__c))?true:false;

                this.interviews.add(wrapper);
            }
        }

        public List<InterviewWrapper> getInterviews(){
            return this.interviews;
        }

    }
}