force-app/main/default/objects/Interview__c/Interview__c.object-meta.xml
<CustomObject>
    <label>Interview</label>
    <nameField>
        <displayFormat>INT-{0000}</displayFormat>
        <label>Interview Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Interview__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Interviews</relationshipLabel>
    <relationshipName>Contact_Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app BACKUP_DELETE/main/default/objects/Interview__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <formula>TEXT(MONTH(DATEVALUE( Interview_Date__c )))+&quot;/&quot; +TEXT(DAY(DATEVALUE( Interview_Date__c )))+&quot;/&quot; +TEXT(YEAR(DATEVALUE( Interview_Date__c )))</formula>
    <label>Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Feedback__c.field-meta.xml
<CustomField>
    <fullName>Feedback__c</fullName>
    <label>Feedback</label>
    <type>TextArea</type>
</CustomField>

force-app BACKUP_DELETE/main/default/objects/Interview__c/fields/Interview_Date__c.field-meta.xml
<CustomField>
    <fullName>Interview_Date__c</fullName>
    <label>Interview Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Interviews</relationshipLabel>
    <relationshipName>Position_Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app BACKUP_DELETE/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Status of the Position</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed - Fulfilled</fullName>
            </value>
            <value>
                <fullName>Closed - Not Fulfilled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Referral__c/Referral__c.object-meta.xml
<CustomObject>
    <label>Referral</label>
    <nameField>
        <displayFormat>R-{000}</displayFormat>
        <label>Referral Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Referrals</relationshipLabel>
    <relationshipName>Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Referrals</relationshipLabel>
    <relationshipName>Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referrer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RecruitingFunctions.cls
public with sharing class RecruitingFunctions {
    @AuraEnabled
    public static RecruitingUtil.Message notifyInterviewerForNewInterview(String recordId, String salesforceUserId, String headerText ){
        RecruitingUtil.Message msg;

        try{
            System.debug('salesforceUserId:' + salesforceUserId);
            System.debug('salesforceUserId:' + String.isEmpty(salesforceUserId));
            salesforceUserId = (String.isEmpty(salesforceUserId))?Userinfo.getUserId():salesforceUserId;
            System.debug('salesforceUserId:' + salesforceUserId);

            //Check to see if the interview record exists before trying it in view
            Interview__c interview = RecruitingData.getInterviewDetails(recordId);
            //text: "A new interview has been scheduled with {!interview.Contact__r.Name} for position {!interview.Position__r.Name} at {!interview.Date__c}"

            String message = UserInfo.getName() +', a new interview has been scheduled with "' + interview.Contact__r.Name + '" for position "' + interview.Position__r.Name + '" at "' + interview.Interview_Date__c + '"';

            Slack.ViewReference viewReference = Slack.View.recruiting_interviewer_notificiation.get();
            viewReference.setParameter('headerText', headerText);
            viewReference.setParameter('recordId', recordId);
            viewReference.setParameter('message', message);
            viewReference.setParameter('label', 'Confirm Interview');
            viewReference.setParameter('action', 'interview_confirm');
            viewReference.setParameter('dispatcher', 'ack');
             
            RecruitingUtilSlack.sendView(RecruitingUtilSlack.getSlackUserId(salesforceUserId), null, viewReference);
            msg = RecruitingUtil.Message.setMsg('Success', true);
        }catch(Exception e){
            msg = RecruitingUtil.Message.setMsg(e.getMessage(), false);
        }
        return msg;
    }
    @AuraEnabled
    public static RecruitingUtil.Message notifyInterviewerForFeedback(String recordId, String salesforceUserId, String headerText ){
        RecruitingUtil.Message msg;
        try{
            salesforceUserId = (String.isEmpty(salesforceUserId))?Userinfo.getUserId():salesforceUserId;

            //Check to see if the interview record exists before trying it in view
            Interview__c interview = RecruitingData.getInterviewDetails(recordId);
            //text: "A new interview has been scheduled with {!interview.Contact__r.Name} for position {!interview.Position__r.Name} at {!interview.Date__c}"

            String message = UserInfo.getName() +', provide feedback for your interview with "' + interview.Contact__r.Name + '" for position "' + interview.Position__r.Name + '" at "' + interview.Interview_Date__c + '"';

            Slack.ViewReference viewReference = Slack.View.recruiting_interviewer_notificiation.get();
            viewReference.setParameter('headerText', headerText);
            viewReference.setParameter('recordId', recordId);
            viewReference.setParameter('message', message);
            viewReference.setParameter('label', 'Provide Feedback');
            viewReference.setParameter('action', 'interview_feedback');
            viewReference.setParameter('dispatcher', 'modal');
             
            RecruitingUtilSlack.sendView(RecruitingUtilSlack.getSlackUserId(salesforceUserId), null, viewReference);
            msg = RecruitingUtil.Message.setMsg('Success', true);
        }catch(Exception e){
            msg = RecruitingUtil.Message.setMsg(e.getMessage(), false);
        }
        return msg;
    }
    public static RecruitingUtil.Message confirmInterview(Id recordId, String status){
        Interview__c interview = RecruitingData.getInterviewDetails(recordId);
        
        // Make sure we can update the database before even trying
        if (!Schema.sObjectType.Interview__c.fields.Status__c.isUpdateable()) {
            return RecruitingUtil.setMsg('You do not have permission to update Interview status', false);
        }
        interview.Status__c = status;
        update interview;

        
        return RecruitingUtil.setMsg('Interview with "' + interview.Contact__r.Name + '" for position "' + interview.Position__r.Name + '" at "' + interview.Interview_Date__c + '" has been Confirmed.', true);
    }   
    public static RecruitingUtil.Message submitInterviewFeedback (Slack.RequestContext context, String recordId) {
        RecruitingUtil.Message msg;
        // Make sure we can update the database before even trying
        if (!Schema.sObjectType.Interview__c.fields.Feedback__c.isUpdateable() &&
        !Schema.sObjectType.Interview__c.fields.Status__c.isUpdateable()) {
            return RecruitingUtil.setMsg('You do not have permission to update Interview feedback', false);
        }
        Map <String, Object> formData = context.getFormData();

        Interview__c interview = RecruitingData.getInterviewDetails(recordId);
        interview.Feedback__c = (String) formData.get('Feedback__c');
        interview.Status__c = 'Feedback Gathered';
        update interview;
        
        
        msg = RecruitingUtil.setMsg('Feedback for interview with "' + interview.Contact__r.Name + '" for position "' + interview.Position__r.Name + '" at "' + interview.Interview_Date__c + '" has been submitted.', true);
        return msg;
    }
    public static RecruitingUtil.Message referFriend (Slack.RequestContext context, String recordId) {
        RecruitingUtil.Message msg;
        // Make sure we can update the database before even trying
        if (!Schema.sObjectType.Referral__c.isCreateable() || !Schema.sObjectType.Referral__c.fields.Contact__c.isCreateable() ||
        !Schema.sObjectType.Referral__c.fields.Position__c.isCreateable() ||
        !Schema.sObjectType.Referral__c.fields.user__c.isCreateable()) {
            return RecruitingUtil.setMsg('You do not have permission to submit referral', false);
        }
        Map <String, Object> formData = context.getFormData();

        System.debug('formData:' + formData);
        Referral__c referral = new Referral__c();
        referral.Contact__c = (String) formData.get('contact_lookup');
        referral.Position__c = (String) formData.get('position_lookup');
        referral.User__c = UserInfo.getUserId();
        insert referral;
        
        msg = RecruitingUtil.setMsg('Referral has been submitted: ' + URL.getSalesforceBaseUrl().toExternalForm() + '/' + referral.Id, true);
        return msg;
    }

    public static void generateHelp(Slack.RequestContext context){
        Slack.ViewReference viewReference = Slack.View.recruiting_help.get();
        
        //Use User client because message is started by user
        //RecruitingUtilSlack.sendView(false, context.getChannelId(), viewReference);
        RecruitingUtilSlack.sendView(context.getChannelId(), context.getUserId(), viewReference);
    }

    public static void cmdInterviews(Slack.RequestContext context, Integer numberOfInterviews, Boolean showOldInterviews){

        Slack.ViewReference viewReference = Slack.View.recruiting_cmd_interviews.get();
        
        viewReference.setParameter('interviewerId', UserInfo.getUserId());
        viewReference.setParameter('showOldInterviews', showOldInterviews);
        viewReference.setParameter('numberOfInterviews', numberOfInterviews);

        //Use User client because message is started by user
        //RecruitingUtilSlack.sendView(false, context.getChannelId(), viewReference);
        RecruitingUtilSlack.sendView(context.getChannelId(), context.getUserId(), viewReference);
    }
}