force-app/main/default/objects/Interview__c/Interview__c.object-meta.xml
<CustomObject>
    <label>Interview</label>
    <nameField>
        <displayFormat>INT-{0000}</displayFormat>
        <label>Interview Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Interview__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Interviews</relationshipLabel>
    <relationshipName>Contact_Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app BACKUP_DELETE/main/default/objects/Interview__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <formula>TEXT(MONTH(DATEVALUE( Interview_Date__c )))+&quot;/&quot; +TEXT(DAY(DATEVALUE( Interview_Date__c )))+&quot;/&quot; +TEXT(YEAR(DATEVALUE( Interview_Date__c )))</formula>
    <label>Date</label>
    <type>Text</type>
</CustomField>

force-app BACKUP_DELETE/main/default/objects/Interview__c/fields/Interview_Date__c.field-meta.xml
<CustomField>
    <fullName>Interview_Date__c</fullName>
    <label>Interview Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Interviews</relationshipLabel>
    <relationshipName>Position_Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app BACKUP_DELETE/main/default/objects/Interviewer__c/Interviewer__c.object-meta.xml
<CustomObject>
    <label>Interviewer</label>
    <nameField>
        <displayFormat>INTW-{0000}</displayFormat>
        <label>Interviewer Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviewers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Interviewer__c/fields/Interview__c.field-meta.xml
<CustomField>
    <fullName>Interview__c</fullName>
    <label>Interview</label>
    <referenceTo>Interview__c</referenceTo>
    <relationshipLabel>Interviewers</relationshipLabel>
    <relationshipName>Interviewers1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app BACKUP_DELETE/main/default/objects/Interviewer__c/fields/Interviewer__c.field-meta.xml
<CustomField>
    <fullName>Interviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Interviewers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interviewer__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <formula>Interview__r.Candidate__r.Position__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Position</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/RecruitingInterviewTriggerHandler.cls
public with sharing class RecruitingInterviewTriggerHandler extends TriggerHandler {
    private Map<Id, Interview__c> newMap;
    private Map<Id, Interview__c> oldMap;
    private List<Interview__c> newInterviews = new List<Interview__c>();

    public RecruitingInterviewTriggerHandler() {
        this.newMap = (Map<Id, Interview__c>) Trigger.newMap;
        this.oldMap = (Map<Id, Interview__c>) Trigger.oldMap;
        this.newInterviews = Trigger.new;

        RecruitingUtil.debug('InterviewTriggerHandler.this.newMap: ' + this.newMap);
        RecruitingUtil.debug('InterviewTriggerHandler.this.oldMap: ' + this.oldMap);
    }
    
    public override void afterUpdate() {
        for(Interview__c rec: newInterviews){
            Interview__c recNew = this.newMap.get(rec.Id);
            Interview__c recOld = this.oldMap.get(rec.Id);
            //If update Interviewer__c is not empty and HAS changed
            if(recNew.Interviewer__c != null  && recNew.Interviewer__c != recOld.Interviewer__c){
                    notifyInterviewerForNewInterview(rec.Id, recNew.Interviewer__c, 'New Interview Scheduled' );
            }
        }
    }
    public override void afterInsert() {
        System.debug('afterInsert: ' + newMap);
    }

    @future
    private static void notifyInterviewerForNewInterview(String recordId, String salesforceUserId, String headerText ){
        RecruitingUtil.Message msg;
        try{

            //Check to see if the interview record exists before trying it in view
            Interview__c interview = RecruitingData.getInterviewDetails(recordId);
            //text: "A new interview has been scheduled with {!interview.Contact__r.Name} for position {!interview.Position__r.Name} at {!interview.Date__c}"

            String message = UserInfo.getName() +', a new interview has been scheduled with "' + interview.Contact__r.Name + '" for position "' + interview.Position__r.Name + '" at "' + interview.Interview_Date__c + '"';

            Slack.ViewReference viewReference = Slack.View.recruiting_interviewer_notificiation.get();
            viewReference.setParameter('headerText', headerText);
            viewReference.setParameter('recordId', recordId);
            viewReference.setParameter('message', message);
             
            RecruitingUtilSlack.sendView(RecruitingUtilSlack.getSlackUserId(salesforceUserId), null, viewReference);
            msg = RecruitingUtil.Message.setMsg('Success', true);
        }catch(Exception e){
            msg = RecruitingUtil.Message.setMsg(e.getMessage(), false);
        }
        
    }
}