force-app/main/default/objects/Interview__c/Interview__c.object-meta.xml
<CustomObject>
    <label>Interview</label>
    <nameField>
        <displayFormat>INT-{0000}</displayFormat>
        <label>Interview Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app BACKUP_DELETE/main/default/objects/Interviewer__c/Interviewer__c.object-meta.xml
<CustomObject>
    <label>Interviewer</label>
    <nameField>
        <displayFormat>INTW-{0000}</displayFormat>
        <label>Interviewer Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviewers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Interviewer__c/fields/Interview__c.field-meta.xml
<CustomField>
    <fullName>Interview__c</fullName>
    <label>Interview</label>
    <referenceTo>Interview__c</referenceTo>
    <relationshipLabel>Interviewers</relationshipLabel>
    <relationshipName>Interviewers1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app BACKUP_DELETE/main/default/objects/Interviewer__c/fields/Interviewer__c.field-meta.xml
<CustomField>
    <fullName>Interviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Interviewers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InterviewTriggerHandler.cls
public with sharing class InterviewTriggerHandler extends TriggerHandler {
    private Map<Id, Interview__c> newMap;
    private Map<Id, Interview__c> oldMap;
    private List<Interview__c> newInterviews = new List<Interview__c>();

    public InterviewTriggerHandler() {
        this.newMap = (Map<Id, Interview__c>) Trigger.newMap;
        this.oldMap = (Map<Id, Interview__c>) Trigger.oldMap;
        this.newInterviews = Trigger.new;

        RecruitingUtil.debug('InterviewTriggerHandler.this.newMap: ' + this.newMap);
        RecruitingUtil.debug('InterviewTriggerHandler.this.oldMap: ' + this.oldMap);
    }
    
    public override void afterUpdate() {
        for(Interview__c rec: newInterviews){
            Interview__c recNew = this.newMap.get(rec.Id);
            Interview__c recOld = this.oldMap.get(rec.Id);
            //If update Interviewer__c is not empty and HAS changed
            if(recNew.Interviewer__c != null  && recNew.Interviewer__c != recOld.Interviewer__c){
                    Recruiting.notifyInterviewerForNewInterviewFuture(rec.Id, recNew.Interviewer__c, 'New Interview' );
            }
        }
    }
    public override void afterInsert() {
        System.debug('afterInsert: ' + newMap);
    }
}